org.gradle.caching=true
group=io.ballerina.lib
version=0.8.2
ballerinaLangVersion=2201.13.0

releasePluginVersion=2.8.0
ballerinaGradlePluginVersion=2.3.0
downloadPluginVersion=5.4.0

# Per-package versions
budgetVersion=0.8.2-SNAPSHOT
cashmanagementVersion=0.8.2-SNAPSHOT
coreVersion=0.8.2-SNAPSHOT
coreorgVersion=0.8.2-SNAPSHOT
customerVersion=0.8.2-SNAPSHOT
customeraccountVersion=0.8.2-SNAPSHOT
customermainVersion=0.8.2-SNAPSHOT
documentVersion=0.8.2-SNAPSHOT
expenseVersion=0.8.2-SNAPSHOT
fiscalVersion=0.8.2-SNAPSHOT
fixedassetVersion=0.8.2-SNAPSHOT
hrVersion=0.8.2-SNAPSHOT
hrdevVersion=0.8.2-SNAPSHOT
journalentryVersion=0.8.2-SNAPSHOT
ledgerVersion=0.8.2-SNAPSHOT
mainaccountVersion=0.8.2-SNAPSHOT
paymentVersion=0.8.2-SNAPSHOT
procurementVersion=0.8.2-SNAPSHOT
projectVersion=0.8.2-SNAPSHOT
receivableVersion=0.8.2-SNAPSHOT
sysconfigVersion=0.8.2-SNAPSHOT
systemVersion=0.8.2-SNAPSHOT
taxVersion=0.8.2-SNAPSHOT
taxregionVersion=0.8.2-SNAPSHOT
tradeVersion=0.8.2-SNAPSHOT
usersVersion=0.8.2-SNAPSHOT
vendorVersion=0.8.2-SNAPSHOT
vendorextendedVersion=0.8.2-SNAPSHOT
vendorpaymentVersion=0.8.2
workflowVersion=0.8.2-SNAPSHOT
