[package]
org = "ballerinax"
name = "microsoft.dynamics365.finance.trade"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Finance Trade", "Area/Compliance", "Vendor/Microsoft", "Dynamics365", "Finance", "ERP", "Type/Connector", "Trade", "Intrastat", "Compliance", "International"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.finance"
icon = "../icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[[package.modules]]
name = "microsoft.dynamics365.finance.trade.mock"

[build-options]
observabilityIncluded = true
