[package]
org = "ballerinax"
name = "microsoft.dynamics365.finance.hr"
version = "0.8.0-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Finance Human Resources", "Area/Human Resources", "Vendor/Microsoft", "Dynamics365", "Finance", "ERP", "Type/Connector", "HR", "Employee", "Worker", "Person"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.finance"
icon = "../icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[[package.modules]]
name = "microsoft.dynamics365.finance.hr.mock"

[build-options]
observabilityIncluded = true
