[package]
org = "wso2"
name = "list_customers"
version = "0.1.0"
distribution = "2201.13.0"

[[dependency]]
org = "ballerinax"
name = "microsoft.dynamics365.finance.customermain"
version = "0.8.0-SNAPSHOT"
repository = "local"
