[package]
org = "ballerinax"
name = "microsoft.dynamics365.finance.system"
version = "0.8.0-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Finance System", "Area/System", "Vendor/Microsoft", "Dynamics365", "Finance", "ERP", "Type/Connector", "System", "Configuration", "Reference"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.finance"
icon = "../icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[[package.modules]]
name = "microsoft.dynamics365.finance.system.mock"

[build-options]
observabilityIncluded = true
