[package]
org = "ballerinax"
name = "microsoft.dynamics365.finance.cashmanagement"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Finance Cash Management", "Area/Finance & Accounting", "Vendor/Microsoft", "Dynamics365", "Finance", "ERP", "Type/Connector", "Bank", "Cash", "Exchange", "Finance"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.finance"
icon = "../icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[[package.modules]]
name = "microsoft.dynamics365.finance.cashmanagement.mock"

[build-options]
observabilityIncluded = true
