[package]
org = "ballerinax"
name = "microsoft.dynamics365.finance.payable"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Finance Payable", "Area/Finance & Accounting", "Vendor/Microsoft", "Dynamics365", "Finance", "ERP", "Payable", "Vendor", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.finance"
icon = "../icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[[package.modules]]
name = "microsoft.dynamics365.finance.payable.mock"

[build-options]
observabilityIncluded = true
