[package]
org = "ballerinax"
name = "microsoft.dynamics365.finance.core"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["Name/Microsoft Dynamics 365 Finance Core", "Area/Finance & Accounting", "Vendor/Microsoft", "Dynamics365", "Finance", "ERP", "Core", "Currency", "LegalEntity", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.dynamics365.finance"
icon = "../icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true
