name: Publish All Connectors to the Ballerina Dev/Stage Central

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        required: true
        options:
          - DEV CENTRAL
          - STAGE CENTRAL

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.set-matrix.outputs.directories }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set matrix for build
        id: set-matrix
        run: |
          folders=()
          cd ballerina
          for dir in $(find . -type d -maxdepth 1 -mindepth 1 | cut -c3-); do
            folders+=("$dir")
          done
          echo "directories=$(jq -nc --args '$ARGS.positional' ${folders[@]})" >> $GITHUB_OUTPUT

  publish:
    name: Publish Connectors
    runs-on: ubuntu-latest
    needs: generate-matrix
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJSON(needs.generate-matrix.outputs.directories) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21.0.3

      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
          if [ -z "$BAL_VERSION" ]; then BAL_VERSION="latest"; fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Run tests on mock
        run: |
          bal test ballerina/${{ matrix.directory }}

      - name: Publish to Dev Central
        if: ${{ inputs.environment == 'DEV CENTRAL' }}
        env:
          BALLERINA_DEV_CENTRAL: true
          BALLERINA_STAGE_CENTRAL: false
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ROOT_VERSION=$(grep -w '^version' gradle.properties | cut -d= -f2 | sed 's/-SNAPSHOT//')
          MODULE_VERSION=$(grep -w '${{ matrix.directory }}Version' gradle.properties | cut -d= -f2 | sed 's/-SNAPSHOT//')
          ./gradlew clean :microsoft.dynamics365.finance-ballerina:${{ matrix.directory }}:build \
            -Pversion=${ROOT_VERSION} -P${{ matrix.directory }}Version=${MODULE_VERSION} \
            -x test -PpublishToCentral=true

      - name: Publish to Stage Central
        if: ${{ inputs.environment == 'STAGE CENTRAL' }}
        env:
          BALLERINA_DEV_CENTRAL: false
          BALLERINA_STAGE_CENTRAL: true
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ROOT_VERSION=$(grep -w '^version' gradle.properties | cut -d= -f2 | sed 's/-SNAPSHOT//')
          MODULE_VERSION=$(grep -w '${{ matrix.directory }}Version' gradle.properties | cut -d= -f2 | sed 's/-SNAPSHOT//')
          ./gradlew clean :microsoft.dynamics365.finance-ballerina:${{ matrix.directory }}:build \
            -Pversion=${ROOT_VERSION} -P${{ matrix.directory }}Version=${MODULE_VERSION} \
            -x test -PpublishToCentral=true
